In [4]:
import pandas  #here we are imported the pandas library
data_frame = pandas.read_csv("data.csv")   #with .read_csv("location/name_of_the_file") it can read the csv file
data_frame.shape  #.shape shows you the shape of the data   #output:- (18207, 89)

(18207, 89)

In [5]:
data_frame.describe()  #it will help to get avarage of the data inside of the given file 
#it will give the output in th eform of : count, std, min, 25%, 50%, 75%, max

,Unnamed: 0,ID,Age,Overall,Potential,Special,International Reputation,Weak Foot,Skill Moves,Jersey Number,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
count,18207.000000,18207.000000,18207.000000,18207.000000,18207.000000,18207.000000,18159.000000,18159.000000,18159.000000,18147.000000,...,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000
mean,9103.000000,214298.338606,25.122206,66.238699,71.307299,1597.809908,1.113222,2.947299,2.361308,19.546096,...,48.548598,58.648274,47.281623,47.697836,45.661435,16.616223,16.391596,16.232061,16.388898,16.710887
std,5256.052511,29965.244204,4.669943,6.908930,6.136496,272.586016,0.394031,0.660456,0.756164,15.947765,...,15.704053,11.436133,19.904397,21.664004,21.289135,17.695349,16.906900,16.502864,17.034669,17.955119
min,0.000000,16.000000,16.000000,46.000000,48.000000,731.000000,1.000000,1.000000,1.000000,1.000000,...,5.000000,3.000000,3.000000,2.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,4551.500000,200315.500000,21.000000,62.000000,67.000000,1457.000000,1.000000,3.000000,2.000000,8.000000,...,39.000000,51.000000,30.000000,27.000000,24.000000,8.000000,8.000000,8.000000,8.000000,8.000000
50%,9103.000000,221759.000000,25.000000,66.000000,71.000000,1635.000000,1.000000,3.000000,2.000000,17.000000,...,49.000000,60.000000,53.000000,55.000000,52.000000,11.000000,11.000000,11.000000,11.000000,11.000000
75%,13654.500000,236529.500000,28.000000,71.000000,75.000000,1787.000000,1.000000,3.000000,3.000000,26.000000,...,60.000000,67.000000,64.000000,66.000000,64.000000,14.000000,14.000000,14.000000,14.000000,14.000000
max,18206.000000,246620.000000,45.000000,94.000000,95.000000,2346.000000,5.000000,5.000000,5.000000,99.000000,...,92.000000,96.000000,94.000000,93.000000,91.000000,90.000000,92.000000,91.000000,90.000000,94.000000

In [7]:
data_frame.values     #it will give you all the data values in the form of arrays
#you will get each user data n an array

array([[0, 158023, 'L. Messi', ..., 14.0, 8.0, 'â‚¬226.5M'],
       [1, 20801, 'Cristiano Ronaldo', ..., 14.0, 11.0, 'â‚¬127.1M'],
       [2, 190871, 'Neymar Jr', ..., 15.0, 11.0, 'â‚¬228.1M'],
       ...,
       [18204, 241638, 'B. Worman', ..., 6.0, 13.0, 'â‚¬165K'],
       [18205, 246268, 'D. Walker-Rice', ..., 8.0, 9.0, 'â‚¬143K'],
       [18206, 246269, 'G. Nugent', ..., 12.0, 9.0, 'â‚¬165K']],
      dtype=object)

In [11]:
# you can filter the data
data_frame[data_frame["Age"] == 25].head()    #here .head means only five of the data shown
# if we remove the .head() it will show all the filtered data

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
9,9,200389,J. Oblak,25,https://cdn.sofifa.org/players/4/19/200389.png,Slovenia,https://cdn.sofifa.org/flags/44.png,90,93,AtlÃ©tico Madrid,...,70.0,27.0,12.0,18.0,86.0,92.0,78.0,88.0,89.0,â‚¬144.5M
43,43,201399,M. Icardi,25,https://cdn.sofifa.org/players/4/19/201399.png,Argentina,https://cdn.sofifa.org/flags/52.png,87,90,Inter,...,85.0,45.0,24.0,20.0,13.0,9.0,5.0,7.0,9.0,â‚¬114.5M
45,45,195864,P. Pogba,25,https://cdn.sofifa.org/players/4/19/195864.png,France,https://cdn.sofifa.org/flags/18.png,87,91,Manchester United,...,87.0,66.0,70.0,68.0,5.0,6.0,2.0,4.0,3.0,â‚¬123.2M
47,47,192505,R. Lukaku,25,https://cdn.sofifa.org/players/4/19/192505.png,Belgium,https://cdn.sofifa.org/flags/7.png,87,89,Manchester United,...,83.0,30.0,30.0,30.0,8.0,15.0,14.0,7.0,10.0,â‚¬120.3M
62,62,201535,R. Varane,25,https://cdn.sofifa.org/players/4/19/201535.png,France,https://cdn.sofifa.org/flags/18.png,86,91,Real Madrid,...,82.0,87.0,88.0,87.0,11.0,11.0,9.0,5.0,14.0,â‚¬106.3M